### ISSUE TITLE
x in demo_test.py

### ISSUE THREAD

**Issue by AakashGfude** [harryhan618/LaneNet#1]
Hello,

Thank you for the code, I wanted to understand what it is use of line 31-32 in demo_test.py where x is declared. Was it supposed to me the argument to net. 

![image](https://user-images.githubusercontent.com/6542997/58377833-9e1bb400-7fb3-11e9-95bc-f7cd1b2356fc.png)

**Comment by harryhan618** [comment]
Yes, you are right. That was a typo.

**Comment by AakashGfude** [comment]
Thank you for the answer. If you have time, can you look at the code below. There seems to be dimensional error specially in lines 50, 51, 52 

![image](https://user-images.githubusercontent.com/6542997/58380292-82c39f80-7fd9-11e9-8e55-89809d411f0b.png)
![image](https://user-images.githubusercontent.com/6542997/58380295-97079c80-7fd9-11e9-81ef-f37834dec4dd.png)

line 27 will be line 52 in the picture code above. lane_seg_img has dimension `288 800` and seg_img has dimension `1 3 288 800`

**Comment by harryhan618** [comment]
Oh, sorry. The intended shape of `seg_img` should be `(288, 800, 3)`, as you can see `seg_img` is later added to origin image in *line 56*. 
So please modify the declaration in *line 46* so that shape of `seg_img` should be `(288, 800, 3)`.

**Comment by AakashGfude** [comment]
Thank you so much. One last question, do you know why the output image has a bluish background to it.

**Comment by harryhan618** [comment]
Could you post the image here? Do you use my provided untested model? Maybe it is the model isn't that accurate. You can use `cv2.imshow("seg_img", seg_img)` to see whether the model result behaves well.

**Comment by harryhan618** [comment]
Please pardon me that the code in this repository is not that well tested compared to my another repository [SCNN](https://github.com/harryhan618/SCNN_Pytorch). And I haven't got more time to refine this one for now. Maybe you can try the other one as well, which also does lane detection.

BTW, during testing, there is a pixel cluster procedure. How is mean shift doing in my code? I think it is very slow by call scikit-learn api and I haven't come up a better idea yet.

**Comment by pangye92** [comment]
Sorry for bothering, I got this problem too. And after I modify the shape of " seg_img" to (288, 800,3), 
I got another error of this pic.
![image](https://user-images.githubusercontent.com/32924915/62943400-f624c280-be0c-11e9-823b-cac3d64f1a31.png)
If you have time could you please help me check it? 
Thanks in advance.

**Comment by pangye92** [comment]
![Selection_003](https://user-images.githubusercontent.com/32924915/62943808-e2c62700-be0d-11e9-9f7c-9e5f5d0db854.png)
