### ISSUE TITLE
about quantitative evaluation

### ISSUE THREAD

**Issue by somebodyus** [harryhan618/LaneNet#11]
When will you publish your test code?
I used the postprocess code from MaybeShewill-CV/lanenet-lane-detection, and I got very low accuracy.

**Comment by harryhan618** [comment]
Hello! What kind of metric do you want for evaluation? mIOU would be easy to implement. So I would update it these days. CULane evaluation is a little bit tricky since this is a binary sementation method. So I would be happy to discuss about it.

**Comment by somebodyus** [comment]
I mean the Accuracy, FP, FN that are defined in the LaneNet paper:
Towards end-to-end lane detection: an instance segmentation approach
