### ISSUE TITLE
Tusimple evaluation resizing

### ISSUE THREAD

**Issue by Msabih** [harryhan618/LaneNet#4]
Hi,

Are you evaluating your model with tusimple ?The tusimple evaluation takes as input h samples and lane points with the size of 720 x 1280 however if we train a network on smaller size then there are two ways to go about it. 

a) resize the network output image to 720 x 1280.

b) resize the points to smaller size and generate y samples/lane points pair.

Which one do you think is best ?

**Comment by harryhan618** [comment]
I think the input size should better be the same size for training. Then the result is calculated in proportion to the origin image size.
This repo is kinda primitive for tusimple dataset. Things will get update later.

**Comment by Msabih** [comment]
Yes, thats the most fair solution but the original points are with respect to 720 x 1280 so training a network will be slower.

So far,  I am testing my model by rescaling the given tusimple benchmark points to the input image size that I feed to the network.

I was just wondering if that would be a fair score and what other users/researchers did.

**Comment by harryhan618** [comment]
Well the input size for training would be smaller than original image size. Maybe you could try size 288 * 512. It's smaller while keeping the aspect ratio.
