### ISSUE TITLE
tiny suggestion, move loss computation outside forward()

### ISSUE THREAD

**Issue by masszhou** [harryhan618/LaneNet#5]
thanks for the sharing!
I read both your implementation of lanenet and SCNN, very clear and elegant.
a small suggestion for lanenet, maybe it would be better to move loss computation outside forward(). Since in inference, we don't need to compute loss

**Comment by harryhan618** [comment]
Thanks a lot! Actually, loss would not get computated if `segLabel` is provided as `None`. This comforms with the reality that we don't have ground truth during inference.
