### ISSUE TITLE
评价指标

### ISSUE THREAD

**Issue by whz1994** [harryhan618/LaneNet#8]
您好，请问您知道怎么在 Tusimple数据集上评估模型性能吗？

**Comment by harryhan618** [comment]
`utils/lane_evaluation/tusimple/lane.py`, 读代码你就知道了。
这个repo尚不完备，你可以star一下我另一个SCNN的repo，那个评估测试脚本基本完备了

**Comment by whz1994** [comment]
请问你什么时候完善lanenet评估呢？

**Comment by harryhan618** [comment]
lanenet是binary的segmentation，可以用meanshift来区分不同的车道线。但是CULane和tusimple上的评估指标需要每个间隔提取x坐标。如果需要这个脚本你可以自己写一下。
sorry，近期比较忙，关于lanenet方法的repo暂时不会补充代码。

**Comment by whz1994** [comment]
好的，谢谢你的回复。





在 2019-09-03 19:30:01，"HarryHan" <notifications@github.com> 写道：


lanenet是binary的segmentation，可以用meanshift来区分不同的车道线。但是CULane和tusimple上的评估指标需要每个间隔提取x坐标。如果需要这个脚本你可以自己写一下。
sorry，近期比较忙，关于lanenet方法的repo暂时不会补充代码。
